name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '⬆️ Dependency upgrades'
    labels:
      - 'bump'
      - 'dependencies'
exclude-labels:
  - 'skip-changelog'
template: |
  ## What's Changed
  $CHANGES
